'MIT License - Copyright (c) 2020-2021 Picorims

@startuml modules
!theme cyborg-outline
skinparam BackgroundColor #222222
skinparam PackageStyle frame

'package: dotted = export, otherwise = import

package "global_context" {}
global_context ..> utils
global_context ..> ui_components
global_context ..> system
global_context ..> electron_ipcRenderer
global_context ..> visual_objects



package "electron_ipcRenderer" {}



package "system" {}
system <.[dotted]. system_info

package "system_info" {}
system_info ..> electron_ipcRenderer



package "ui_components" {}
ui_components <.[dotted]. ui_base_components
ui_components <.[dotted]. ui_parameters
ui_components <.[dotted]. ui_append_help

package "ui_base_components" {}
ui_base_components ..> utils

package "ui_parameters" {}
ui_parameters ..> utils
ui_parameters ..> ui_base_components
ui_parameters ..> ui_append_help

package "ui_append_help" {}
ui_append_help ..> utils
ui_append_help ..> ui_base_components



package "utils" {}
utils <.[dotted]. type_checking
utils <.[dotted]. randomizers
utils <.[dotted]. array_utils
utils <.[dotted]. log
utils <.[dotted]. event_mixin
utils <.[dotted]. object_utils

package "array_utils" {}
array_utils ..> type_checking

package "randomizers" {}
randomizers ..> type_checking

package "type_checking" {}

package "log" {}
log ..> electron_ipcRenderer

package "event_mixin" {}

package "object_utils" {}
object_utils ..> type_checking



package "visual_objects" {}
visual_objects <.[dotted]. visual_object
visual_objects <.[dotted]. visual_object_property

package "visual_object" {}
visual_object ..> ui_components
visual_object ..> utils
visual_object ..> visual_object_property

package "visual_object_property" {}
visual_object_property ..> visual_object
visual_object_property ..> utils
visual_object_property ..> ui_components

@enduml