'MIT License - Copyright (c) 2020-2021 Picorims

@startuml ui_loading_frame
!theme cyborg-outline
skinparam BackgroundColor #222222
' skinparam groupInheritance 2
skinparam PackageStyle frame

package "ui_base_components" {
    class UIComponent {}
}

package "ui_loading_frame" {
    class UILoadingFrame {
        - _TIMEOUT: Number
        - _visible: Boolean
        --
        + UILoadingFrame(): UILoadingFrame
        ..
        + show(): void
        + hide(): void
    }
    UIComponent <|-- UIHelp
}

@enduml